//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.StudentRegistration
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Registration.
    /// </summary>
    // *** Start programmer edit section *** (Registration CustomAttributes)

    // *** End programmer edit section *** (Registration CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("RegistrationE", new string[] {
            "DateOfRegistration as \'Date of registration\'",
            "CourseType as \'Course type\'",
            "Course as \'Course\'",
            "Course.Name as \'Name\'",
            "Student as \'Student\'",
            "Student.Surname as \'Surname\'"}, Hidden=new string[] {
            "Course.Name",
            "Student.Surname"})]
    [MasterViewDefineAttribute("RegistrationE", "Course", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Name")]
    [MasterViewDefineAttribute("RegistrationE", "Student", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Surname")]
    [View("RegistrationL", new string[] {
            "DateOfRegistration as \'Date of registration\'",
            "CourseType as \'Course type\'",
            "Course.Name as \'Name\'",
            "Student.Surname as \'Surname\'"})]
    public class Registration : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fDateOfRegistration;
        
        private IIS.StudentRegistration.tCourseType fCourseType;
        
        private IIS.StudentRegistration.Course fCourse;
        
        private IIS.StudentRegistration.Student fStudent;
        
        // *** Start programmer edit section *** (Registration CustomMembers)

        // *** End programmer edit section *** (Registration CustomMembers)

        
        /// <summary>
        /// DateOfRegistration.
        /// </summary>
        // *** Start programmer edit section *** (Registration.DateOfRegistration CustomAttributes)

        // *** End programmer edit section *** (Registration.DateOfRegistration CustomAttributes)
        public virtual System.DateTime DateOfRegistration
        {
            get
            {
                // *** Start programmer edit section *** (Registration.DateOfRegistration Get start)

                // *** End programmer edit section *** (Registration.DateOfRegistration Get start)
                System.DateTime result = this.fDateOfRegistration;
                // *** Start programmer edit section *** (Registration.DateOfRegistration Get end)

                // *** End programmer edit section *** (Registration.DateOfRegistration Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Registration.DateOfRegistration Set start)

                // *** End programmer edit section *** (Registration.DateOfRegistration Set start)
                this.fDateOfRegistration = value;
                // *** Start programmer edit section *** (Registration.DateOfRegistration Set end)

                // *** End programmer edit section *** (Registration.DateOfRegistration Set end)
            }
        }
        
        /// <summary>
        /// CourseType.
        /// </summary>
        // *** Start programmer edit section *** (Registration.CourseType CustomAttributes)

        // *** End programmer edit section *** (Registration.CourseType CustomAttributes)
        public virtual IIS.StudentRegistration.tCourseType CourseType
        {
            get
            {
                // *** Start programmer edit section *** (Registration.CourseType Get start)

                // *** End programmer edit section *** (Registration.CourseType Get start)
                IIS.StudentRegistration.tCourseType result = this.fCourseType;
                // *** Start programmer edit section *** (Registration.CourseType Get end)

                // *** End programmer edit section *** (Registration.CourseType Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Registration.CourseType Set start)

                // *** End programmer edit section *** (Registration.CourseType Set start)
                this.fCourseType = value;
                // *** Start programmer edit section *** (Registration.CourseType Set end)

                // *** End programmer edit section *** (Registration.CourseType Set end)
            }
        }
        
        /// <summary>
        /// Registration.
        /// </summary>
        // *** Start programmer edit section *** (Registration.Course CustomAttributes)

        // *** End programmer edit section *** (Registration.Course CustomAttributes)
        [NotNull()]
        public virtual IIS.StudentRegistration.Course Course
        {
            get
            {
                // *** Start programmer edit section *** (Registration.Course Get start)

                // *** End programmer edit section *** (Registration.Course Get start)
                IIS.StudentRegistration.Course result = this.fCourse;
                // *** Start programmer edit section *** (Registration.Course Get end)

                // *** End programmer edit section *** (Registration.Course Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Registration.Course Set start)

                // *** End programmer edit section *** (Registration.Course Set start)
                this.fCourse = value;
                // *** Start programmer edit section *** (Registration.Course Set end)

                // *** End programmer edit section *** (Registration.Course Set end)
            }
        }
        
        /// <summary>
        /// Registration.
        /// </summary>
        // *** Start programmer edit section *** (Registration.Student CustomAttributes)

        // *** End programmer edit section *** (Registration.Student CustomAttributes)
        [NotNull()]
        public virtual IIS.StudentRegistration.Student Student
        {
            get
            {
                // *** Start programmer edit section *** (Registration.Student Get start)

                // *** End programmer edit section *** (Registration.Student Get start)
                IIS.StudentRegistration.Student result = this.fStudent;
                // *** Start programmer edit section *** (Registration.Student Get end)

                // *** End programmer edit section *** (Registration.Student Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Registration.Student Set start)

                // *** End programmer edit section *** (Registration.Student Set start)
                this.fStudent = value;
                // *** Start programmer edit section *** (Registration.Student Set end)

                // *** End programmer edit section *** (Registration.Student Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "RegistrationE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View RegistrationE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("RegistrationE", typeof(IIS.StudentRegistration.Registration));
                }
            }
            
            /// <summary>
            /// "RegistrationL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View RegistrationL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("RegistrationL", typeof(IIS.StudentRegistration.Registration));
                }
            }
        }
    }
}
