//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.StudentRegistration
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Course Type.
    /// </summary>
    // *** Start programmer edit section *** (tCourseType CustomAttributes)

    // *** End programmer edit section *** (tCourseType CustomAttributes)
    public enum tCourseType
    {
        
        /// <summary>
        /// Programming.
        /// </summary>
        // *** Start programmer edit section *** (tCourseType.Programming CustomAttributes)

        // *** End programmer edit section *** (tCourseType.Programming CustomAttributes)
        Programming,
        
        /// <summary>
        /// Finance.
        /// </summary>
        // *** Start programmer edit section *** (tCourseType.Finance CustomAttributes)

        // *** End programmer edit section *** (tCourseType.Finance CustomAttributes)
        Finance,
        
        /// <summary>
        /// Management.
        /// </summary>
        // *** Start programmer edit section *** (tCourseType.Management CustomAttributes)

        // *** End programmer edit section *** (tCourseType.Management CustomAttributes)
        Management,
        
        /// <summary>
        /// Business Analytics.
        /// </summary>
        // *** Start programmer edit section *** (tCourseType.Analytics CustomAttributes)

        // *** End programmer edit section *** (tCourseType.Analytics CustomAttributes)
        Analytics,
    }
}
