//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.StudentRegistration
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Course Type.
    /// </summary>
    // *** Start programmer edit section *** (tCourseType CustomAttributes)

    // *** End programmer edit section *** (tCourseType CustomAttributes)
    public enum tCourseType
    {
        
        // *** Start programmer edit section *** (tCourseType.Programming CustomAttributes)

        // *** End programmer edit section *** (tCourseType.Programming CustomAttributes)
        [Caption("Programming")]
        Programming,
        
        // *** Start programmer edit section *** (tCourseType.Analytics CustomAttributes)

        // *** End programmer edit section *** (tCourseType.Analytics CustomAttributes)
        [Caption("Business Analytics")]
        Analytics,
        
        // *** Start programmer edit section *** (tCourseType.Finance CustomAttributes)

        // *** End programmer edit section *** (tCourseType.Finance CustomAttributes)
        [Caption("Finance")]
        Finance,
        
        // *** Start programmer edit section *** (tCourseType.Management CustomAttributes)

        // *** End programmer edit section *** (tCourseType.Management CustomAttributes)
        [Caption("Management")]
        Management,
    }
}
